<b>Задание:</b> реализовать скалярное произведение векторов тремя способами:
<ol>
    <li>Через цикл</li>
    <li>Через векторное умножение</li>
    <li>Через транспонирование</li>
</ol>
В задании потребуется создать два любых <i>вектора столбца</i> и продемонстрировать работу на них.<br>
<b>Напоминание:</b> скалярное произведение(или взвешенная сумма) - это мера близости двух векторов, которая вычисляется по следующей формуле:<br>
$
\overline{V}=(v_{1}, v_{2}, . . ., v_{i})
$<br>
$
\overline{U}=(u_{1}, u_{2}, . . ., u_{i})
$, тогда $
\left\langle V, U \right\rangle = \sum_{j=1}^{i}v_{j}\cdot u_{j}
$<br>
Или: $
\left\langle V, U \right\rangle = U^{T}V
$

In [1]:
import numpy as np

In [2]:
def scalar_1(u, v):
    res = 0
    for i in range(len(u)):
        res += u[i] * v[i]
    return res

def scalar_2(u, v):
    return np.sum(u * v)

def scalar_3(u, v):
    return np.dot(u.T, v)

In [3]:
a = np.array([1, 2, 3]).reshape(3, -1)
b = np.array([4, 5, 6]).reshape(3, -1)

In [4]:
a, b

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]))

In [5]:
scalar_1(a, b)

array([32])

In [6]:
scalar_2(a, b)

32

In [7]:
scalar_3(a, b)

array([[32]])